---
- name: Clone techvomit repo
  git:
    repo: git://github.com/l50/techvomit.git
    dest: "{{techvomit_directory}}"

- name: Copy creds env file into place
  copy:
    src: env
    dest: "{{techvomit_directory}}/.env"

- name: Move backed up data into place
  copy:
    src: backups
    dest: "{{techvomit_directory}}"

- name: Unzip Ghost backup
  shell: "unzip {{ghost_backup_zip}} -d {{ghost_backup}}"

- name: Unzip MariaDB backup
  shell: "unzip {{mariadb_backup_zip}} -d {{mariadb_backup}}"

- name: docker-compose up to get the folder infrastructure built up
  shell: "docker-compose up -d"
  args:
    chdir: "{{techvomit_directory}}"

- name: Wait until the blog is finished with initial setup
  pause:
    minutes: 2

- name: Stop techvomit containers so we can move data into place
  shell: "docker-compose stop"
  args:
    chdir: "{{techvomit_directory}}"

- name: Rsync MariaDB data
  shell: "rsync -a {{mariadb_backup}}/_data/ {{mariadb_data}}"

- name: Transfer aio theme
  shell: "cp -r {{aio_backup}} {{ghost_data}}/_data/ghost/content/themes/"

# TODO: We should be able to remove this once we can test our new docker-compose
# BEGIN
- name: Create ssl certificate directory
  file: path="{{ssl_directory}}/ssl" state=directory

- name: Move backed up data into place
  copy:
    src: "ssl.zip"
    dest: "{{techvomit_directory}}/ssl.zip"

- name: Unzip ssl certificate zip
  unarchive:
    src: "{{techvomit_directory}}/ssl.zip"
    dest: "{{ssl_directory}}"
    remote_src: yes
#END

- name: Force rebuild to incorporate the data
  shell: "docker-compose up -d --force-recreate"
  args:
    chdir: "{{techvomit_directory}}"
